services:
    database:
        image: mysql
        container_name: database
        restart: unless-stopped
        environment:
            MYSQL_PASSWORD: 2535455m
            MYSQL_DB: laravel_docker
        volumes:
            - ./mysql-data:/var/lib/mysql/data
        ports:
            - '3306:3036'


    php-apache:
        container_name: php-apache
        build:
            context: ./php
        ports:
            - '8080:80'
        volumes:
            - ./var/www/laravel_docker
        depends_on:
            - database
